### ISSUE TITLE
Suggest using "Devel::CheckLib"

### ISSUE THREAD

**Issue by benkasminbullock** [polettix/Graphics-Potrace#2]
May I suggest using [Devel::CheckLib](http://search.cpan.org/perldoc?Devel::CheckLib) to check for the potrace library? At the moment it's necessary to actually edit the Makefile.PL to the library location. [Here](https://metacpan.org/source/BKB/Image-PNG-0.20/Makefile.PL) is an example of using Devel::CheckLib.

**Comment by polettix** [comment]
Done that at the very last. Change is in latest commits, and the CPAN version is on the way (I already see it at https://metacpan.org/release/POLETTIX/Graphics-Potrace-0.74)
